### ISSUE TITLE
GitHub rest_commands

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#103]
# GitHub API

## Rest command
Using the rest_command integrated I created the following service.
```
rest_command:
  new_github_issue_replace_battery:
    url: https://api.github.com/repos/jcallaghan/home-assistant-config/issues
    method: POST
    headers:
      Authorization: !secret github_token
    payload: '{"title":"{{ title }}","body":"{{ message }}","labels":["battery","task: maintenance"]}'
```

### secrets.yaml
Don't forget to add ```Bearer ``` in front of your access token in your secrets file.
```
github_token: "Bearer 000000000000000"
```

## Automation/service

Service name:
```rest_command.new_github_issue_replace_battery```
Service data: 
```
{ 
  "title": "Service test",
  "message": "Create via service call in Home Assistant"
}
```
![image](https://user-images.githubusercontent.com/7449908/84329850-bbe79700-ab7d-11ea-98ee-f7ac1099741d.png)

## Reference
* https://developer.github.com/v3/issues/#create-an-issue
* https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens
* https://www.postman.com/
* https://developer.github.com/v3/
* https://www.home-assistant.io/integrations/rest_command/

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/60#issuecomment-642597169_
