### ISSUE TITLE
Hot tub water quality

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#12]
The hot tub requires pH, alkalinity and free chlorine levels to be maintained. The levels of these need to be tested daily using dip test strips and chemicals added to maintain appropriate water quality.

I want to add sensors to help me with this task but also learn about water quality and the chemicals I am adding to my hot tub. So my plan is to try and monitor the following:
* [x] Temperature (Dallas temperature probe)
* [x] Tds (Bewinner1 TDS sensor)
* [ ] pH (Garsent digital pH sensor)
* [ ] Alkalinity
* [ ] Free chlorine

### Hot tub specifics
Type | Measurement
-- | --
pH | 7.4-7.6
Total  Alkalinity | 80-120ppm
Free Chlorine | 2-4ppm
Volume | 795L

**Comment by jcallaghan** [comment]
Using native ESPHome integration for [Dallas temperature probe](https://esphome.io/components/sensor/dallas.html).

```yaml
dallas:
  - pin: GPIO21

sensor:
  - platform: dallas
    address: 0x770316457608FF28
    name: "${system_name}_temperature"
```

**Comment by jcallaghan** [comment]
I'm using a single ESP32 for all of these sensors.
```yaml 
esphome:
  name: ${system_name}
  platform: ESP32
  board: pico32

**Comment by jcallaghan** [comment]
The TDS sensor is of the same kind available from [Seed Studio](https://www.seeedstudio.com/Grove-TDS-Sensor-p-4400.html) and they have a great [blog article about the sensor](https://www.seeedstudio.com/blog/2020/01/19/tds-in-water-what-is-tds-and-how-do-you-measure-tds-in-water/). Amongst the sample sketch they've provided there is a calculation which converrts the value returned from the sensor (v) to TDS ppm value.
```yaml
filters:
      - lambda: return (133.42*x*x*x - 255.86*x*x + 857.39*x)*0.5;
```
To integrate this with ESPHome I am using the [ADC integration](https://esphome.io/components/sensor/adc.html) and a [filter to allow me to capture a moving average](https://esphome.io/components/sensor/index.html#sensor-filters) while also capturing data regularly. This prevents fluctuations in the recorded data. 
```yaml
sensor:
  - platform: adc
    pin: GPIO34
    name: "${system_name}_tds"
    update_interval: 10s
    unit_of_measurement: "ppm"
    icon: "mdi:water-percent"
    filters:
      - lambda: return (133.42*x*x*x - 255.86*x*x + 857.39*x)*0.5;
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
```

**Comment by jcallaghan** [comment]
[Sharing the project on Twitter](https://twitter.com/jamescallaghan/status/1253683005727653888).

**Comment by jcallaghan** [comment]
## TDS water quality test results
* 0.5m lead from the breakout board
  * Milk = 400ppm
  * Tap water = 40ppm
* 5m lead from the breakout board
  * Milk = 405ppm
  * Water = 360ppm
  * Hot tub water (few weeks old and chemicals) = 400ppm

**Comment by jcallaghan** [comment]
![Hands on for the first time with some milk and water for testing](https://user-images.githubusercontent.com/7449908/80229576-8a0b8700-8648-11ea-9dd4-fa28a8864fad.jpeg)

**Comment by jcallaghan** [comment]
Last weekend I added too much foam remover to the hot tub. To avoid poor water quality and remove the weird white bits that also formed in the water I added some fresh water to the hot tub. The intention was to leave the hose on for 30 minutes or so and let the bad water overfill except I forgot I was running water into the hot tub and I woke a 2am in a panic the hose was still running. I promptly got up, disarmed the house, went downstairs, unlocked the patio and went out and turned the tap off. I then reversed all this and went back to bed. Whilst struggling to sleep I decided I wasn't going to be doing this again. Two things that will help me. 

One, an automation to notify me if the temperature drops in the hot tub which is an indication although I plan to make this a little more sophisticated than it currently is and two a solenoid to turn the water tap on and off.

```yaml
alias: 'Hot Tub - Water temperature falling'

trigger:

  # trigger when the water temperature falls below 35c
  - platform: numeric_state
    entity_id: sensor.esph_hot_tub_water_temperature
    below: '35'

condition:

  # check the automation has not run within the last 60 minutes
  - condition: template
    value_template: "{{ (as_timestamp(states.sensor.date_time.last_changed) - (as_timestamp(state_attr('automation.hot_tub_water_temperature_falling','last_triggered')))) > 3600 }}"

action:

  - service: notify.html5_notification
    data_template:
      title: "Hot Tub water temperature"
      message: "The hot tub water is at {{ states('sensor.esph_hot_tub_water_temperature') }} and falling."

  - service: notify.ios_james_iphone
    data_template:
      title: "Hot Tub water temperature"
      message: "The hot tub water is at {{ states('sensor.esph_hot_tub_water_temperature') }} and falling."
```
