### ISSUE TITLE
Lovelace - Utility

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#214]
Here is a panel for two cupboards I use as a utility. 

![image](https://user-images.githubusercontent.com/7449908/86977157-e83e0580-c173-11ea-98f7-b0ec95aa6d23.png)

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/207#issuecomment-655783223_

**Comment by jcallaghan** [comment]
## Vertical and horizontal stacks

![image](https://user-images.githubusercontent.com/7449908/86975510-5ed90400-c170-11ea-995e-6f2a028282b5.png)

```
cards:
  - cards:
      - entity: light.washing_machine_cupboard_light
        hold_action:
          action: more-info
        icon_height: 75px
        name: Washing Machine
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: button
      - entity: light.understairs_cupboard_light
        hold_action:
          action: more-info
        icon_height: 75px
        name: Understairs
        show_icon: true
        show_name: true
        tap_action:
          action: toggle
        type: button
    type: horizontal-stack
  - cards:
      - entities:
          - entity: binary_sensor.washing_machine_cupboard_motion
          - entity: sensor.washing_machine_cupboard_motion_lux
        show_name: false
        type: glance
      - entities:
          - entity: binary_sensor.understairs_cupboard_motion
          - entity: sensor.understairs_cupboard_motion_lux
        show_name: false
        type: glance
    type: horizontal-stack
  - cards:
      - detail: 2
        entity: sensor.washing_machine_cupboard_motion_temperature
        graph: line
        name: Washing Machine
        type: sensor
      - detail: 2
        entity: sensor.understairs_cupboard_motion_temperature
        graph: line
        name: Understairs
        type: sensor
    type: horizontal-stack
type: vertical-stack
```

Here is the same example just using two separate vertical stacks.

![image](https://user-images.githubusercontent.com/7449908/86976855-4dddc200-c173-11ea-8294-b06f107e7e84.png)
