### ISSUE TITLE
Automatic herb watering system 🚿🌿👨‍🍳

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#222]
Document the build of an automatic watering system for my kitchen garden herbs. The plan is to upgrade my existing watering solution and integrate it with Home Assistant with a friend who wants to do the same with his outdoor herbs.

### Ingredients
* Water container
* 5V water pump
* D1 Mini controller running ESPHome
* Soil moisture sensors
* Low water circuit
* Flower Care sensor
* UV light
* Home Assistant helpers and automation to drive watering schedule

Related: #174

**Comment by jcallaghan** [comment]
This is my existing pump unit - https://www.amazon.co.uk/gp/product/B07PDM4KSC/

**Comment by jcallaghan** [comment]
This is the UV light I brought which I will likely upgrade to something large that I can fit on the ceiling https://www.amazon.co.uk/gp/product/B07GB28WCH

**Comment by jcallaghan** [comment]
Solar-powered watering system example https://twitter.com/zimmergren/status/1282599157732126721

**Comment by jcallaghan** [comment]
https://www.amazon.co.uk/gp/product/B07GB28WCH

**Comment by bryanbr23** [comment]
Food for thought: https://www.splitbrain.org/blog/2017-06/10-automated_plant_watering

**Comment by jcallaghan** [comment]
# Test Helpers and Automation

As this was all tested without the ESPHome node some fake entities were created so the automation could be created and tested. All fake entities need to be replaced. It assumes an ESPHome device would provide a moisture sensor and a relay/switch for the pump.

The automation has some ```//TODO``` items but two considerations or improvements are catching when the pump last ran. This is currently checked via the ```last_triggered ```attribute from the ```automation```. I'm not sure if the state will persist after a reboot so worth considering leveraging a ```date_time ```helper. The other item is the time between runs, effectively a throttle to avoid the automation running multiple times. This is currently driven by an ```input_number ```helper and assumes the pump runs once a day. This is an area I'd like to spend a little more time on.

![image](https://user-images.githubusercontent.com/7449908/87782979-76c51d80-c82b-11ea-91d2-9c8d1a621800.png)

### Automation
```yaml
alias: 'Zone 1 Watering'

trigger:

  # When the moisture falls below the moisture low threshold.
  - platform: template
    value_template: "{{ states('input_number.fake_zone1_moisture') | int < states('input_number.fake_zone1_moisture_threshold') | int }}"

  # When the time matches the water at helper.
  - platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.fake_zone1_water_time1','timestamp') | int | timestamp_custom('%H:%M', False)) }}"

condition:

  condition: and
  conditions:

    # Only run once a day (86400 seconds in a day).
    # //TODO Consider using an input_datetime helper to avoid issues with Home Assistant restarts.
    # //TODO Move throttling time to a input_number help and allow the throttling to be changed in the UI [Done].
    # //TODO This might also need to be considered as a trigger too.
    - condition: template
      value_template: "{{ (as_timestamp(states.sensor.date_time.last_changed) - (as_timestamp(state_attr('automation.zone_1_watering','last_triggered')))) > (states('fake_zone1_time_between_watering') | int * 60) }}"

    # Watering must only occur whe the moisture is below the moisture low threshold.
    - condition: template
      value_template: "{{ states('input_number.fake_zone1_moisture') | int < states('input_number.fake_zone1_moisture_threshold') | int }}"

    # This automatic water enabled helper must be enabled for automatic watering to work.
    - condition: state
      entity_id: input_boolean.fake_zone1_enabled
      state: "on"

    # The pump should not be activated if the water is low.
    - condition: state
      entity_id: input_boolean.fake_zone1_water_available
      state: "on"

action:

  # Turn on the pump.
  - service: input_boolean.turn_on
    entity_id: input_boolean.fake_zone1_switch

  # Add a delay to allow the pump to work based on how long we want it to run for in the UI.
  - delay:
      seconds: "{{ states('input_number.fake_zone1_pump_run_time') | int }}"

  # Turn off the pump.
  - service: input_boolean.turn_off
    entity_id: input_boolean.fake_zone1_switch

  # //TODO check-in notification. Send notification to say the plants have been watered and their moisture level was 20% and is now 56%. Grow biggy grow! 🌻

# //TODO consider creating a secondary automation to send a notification/alert when the water is low.

# Tests
# 1. The automation should only work when "automatic watering enabled" and "Water Available" are both on.
# 1. The automation will only run after the duration "xxxx" has passed since it last ran.
# 1. The automation should trigger when the "Moisture Level" from the plant falls below the "Moisture Level Threshold" or the time matches "Water at".
# 1. The pump should only run for the duration set via "Pump Run Time".

```
### input_boolean helpers
```
fake_zone1_enabled:
  name: Automatic Watering Enabled
  icon: mdi:watering-can

fake_zone1_switch:
  name: Pump
  icon: mdi:pump

fake_zone1_water_available:
  name: Water Available
  icon: mdi:water-off
````
### input_number helpers
```
fake_zone1_moisture:
  name: Moisture Level
  min: 0
  max: 100
  step: 1
  unit_of_measurement: "%"
  mode: box

fake_zone1_moisture_threshold:
  name: Moisture Low Threshold
  min: 0
  max: 100
  step: 1
  unit_of_measurement: "%"

fake_zone1_pump_run_time:
  name: Pump Run Time
  min: 0
  max: 60
  step: 1
  unit_of_measurement: "seconds"

fake_zone1_time_between_watering:
  name: Minimum time between watering
  min: 0
  max: 1440
  step: 1
  unit_of_measurement: "minutes"
  mode: box

```
