### ISSUE TITLE
Nest smoke alarm integration 🔥🚨🧯

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#225]
## Objective

Integrate Nest Protect smoke alarms with Home Assistant. 

### Goals

- [x] [Lovelace dashboard](https://github.com/jcallaghan/home-assistant-config/issues/225#issuecomment-1074071880)
- [ ] Automation, enable lights, open blinds, pause/stop media-players etc.
- [ ] Actionable notifications
- [ ] Integration with internal/external sirens
- [ ] Monitor batteries and health-checks
- [ ] Extended family & friends notification/alert

## Related

- #60 
- #220

**Comment by CCOSTAN** [comment]
Did you check out Bad nest? 

I'm able to have mine integrated but I've had my developer account for years. 
https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/nest_protects.yaml

**Comment by jcallaghan** [comment]
I've not and my Google Developer account was migrated sadly.

Paulus suggested the API might be opening back up again soon (source "Hey Google" smart home summit). https://twitter.com/balloob/status/1280923380313501697

**Comment by jcallaghan** [comment]
## Nest Protect integration

I came across @iMicknl's [Nest Protect integration for Home Assistant](https://github.com/iMicknl/ha-nest-protect). This solves my Nest Project integration problem until Google SDM finally gets around to supporting Nest Protects.

I have created a Security & Safety Lovelace dashboard where we have dedicated panels relating to the different aspects of security and safety in our home, this now includes our Smoke Alarms! This panel shows me useful information from each of my Nest Protect units.

Below are examples of two cards I created. Note: I am leveraging [Simple Icons](https://github.com/vigonotion/hass-simpleicons) for the header icon and [multiple-entity-row card](https://github.com/benct/lovelace-multiple-entity-row). I plan to add a few additional units and have stuck with the last example for now.

![image](https://user-images.githubusercontent.com/7449908/159293403-cd6a2bc8-c16e-463d-8b10-49f7c400ac41.png)

```yaml
type: entities
entities:
  - type: weblink
    url: https://home.nest.com/protect/
    name: Nest Project Dashboard
  - type: section
    label: Nodes
  - entity: device_tracker.appliance_nest_protect_downstairs
    icon: mdi:smoke-detector
    name: Downstairs
    secondary_info: last-updated
  - entity: device_tracker.appliance_nest_protect_upstairs
    icon: mdi:smoke-detector
    name: Upstairs
    secondary_info: last-updated
  - type: section
    label: Status
  - entity: binary_sensor.nest_protect_upstairs_co_status
    type: custom:multiple-entity-row
    name: Carbon Monoxide (CO)
    secondary_info: last-changed
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_downstairs_co_status
        name: Downstairs
      - entity: binary_sensor.nest_protect_upstairs_co_status
        name: Upstairs
  - entity: binary_sensor.nest_protect_upstairs_heat_status
    type: custom:multiple-entity-row
    name: Heat
    secondary_info: last-changed
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_downstairs_heat_status
        name: Downstairs
      - entity: binary_sensor.nest_protect_upstairs_heat_status
        name: Upstairs
  - entity: binary_sensor.nest_protect_upstairs_smoke_status
    type: custom:multiple-entity-row
    name: Smoke
    secondary_info: last-changed
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_downstairs_smoke_status
        name: Downstairs
      - entity: binary_sensor.nest_protect_upstairs_smoke_status
        name: Upstairs
  - entity: binary_sensor.nest_protect_downstairs_battery_health
    type: custom:multiple-entity-row
    name: Battery Health
    secondary_info: last-changed
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_downstairs_battery_health
        name: Downstairs
      - entity: binary_sensor.nest_protect_upstairs_battery_health
        name: Upstairs
state_color: true
show_header_toggle: false
title: Nest Protect
icon: si:google
view_layout:
  position: sidebar
header:
  type: picture
  image: /local/images/brand/nest-project-product.png
  tap_action:
    action: none
  hold_action:
    action: none
```

![image](https://user-images.githubusercontent.com/7449908/159298460-040ec088-96ea-4f1e-b888-0e34109a2d8d.png)

```yaml
type: entities
entities:
  - type: weblink
    url: https://home.nest.com/protect/
    name: Nest Project Dashboard
  - type: section
    label: Status
  - entity: device_tracker.appliance_nest_protect_downstairs
    type: custom:multiple-entity-row
    icon: mdi:smoke-detector
    name: Downstairs
    secondary_info: last-updated
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_downstairs_co_status
        name: CO
      - entity: binary_sensor.nest_protect_downstairs_heat_status
        name: Heat
      - entity: binary_sensor.nest_protect_downstairs_smoke_status
        name: Smoke
      - entity: binary_sensor.nest_protect_downstairs_battery_health
        name: Battery
  - entity: device_tracker.appliance_nest_protect_upstairs
    type: custom:multiple-entity-row
    icon: mdi:smoke-detector
    name: Upstairs
    secondary_info: last-updated
    show_state: false
    entities:
      - entity: binary_sensor.nest_protect_upstairs_co_status
        name: CO
      - entity: binary_sensor.nest_protect_upstairs_heat_status
        name: Heat
      - entity: binary_sensor.nest_protect_upstairs_smoke_status
        name: Smoke
      - entity: binary_sensor.nest_protect_upstairs_battery_health
        name: Battery
  - type: section
    label: Nodes
  - entity: device_tracker.appliance_nest_protect_downstairs
    icon: mdi:smoke-detector
    name: Downstairs
    secondary_info: last-updated
  - entity: device_tracker.appliance_nest_protect_upstairs
    icon: mdi:smoke-detector
    name: Upstairs
    secondary_info: last-updated
state_color: true
show_header_toggle: false
title: Nest Protect
icon: si:google
view_layout:
  position: sidebar
header:
  type: picture
  image: /local/images/brand/nest-project-product.png
  tap_action:
    action: none
  hold_action:
    action: none
```

**Comment by jcallaghan** [comment]
## Lovelace

Here is the Lovelace card I have settled with for now. I think this will work well with additional Nest Protects.

![image](https://user-images.githubusercontent.com/7449908/159369007-b5b017eb-f6e0-4673-bb46-4fd788548b41.png)

I also show more information when debug mode is enabled. Debug mode is something I've setup to show me more information or send me additional information in notifications. It's just an ```input_boolean``` helper that I toggle on and off as and when needed.

![image](https://user-images.githubusercontent.com/7449908/159369562-cf8c8c48-7be6-4691-a25d-ec2cb8f56c10.png)

### YAML

```yaml
type: vertical-stack
cards:
  - type: entities
    entities:
      - type: weblink
        url: https://home.nest.com/protect/
        name: Nest Project Dashboard
        icon: mdi:open-in-new
      - type: weblink
        url: x/appliances/Smoke-Alarms/Smoke-Alarms.md
        name: Household Wiki > Appliances > Smoke Alarms
        icon: si:markdown
      - type: section
        label: Smoke Alarms
      - entity: device_tracker.appliance_nest_protect_downstairs
        type: custom:multiple-entity-row
        icon: mdi:smoke-detector
        name: Downstairs
        secondary_info: last-updated
        show_state: false
        entities:
          - entity: binary_sensor.nest_protect_downstairs_co_status
            name: CO
          - entity: binary_sensor.nest_protect_downstairs_heat_status
            name: Heat
          - entity: binary_sensor.nest_protect_downstairs_smoke_status
            name: Smoke
          - entity: binary_sensor.nest_protect_downstairs_battery_health
            name: Battery
          - entity: device_tracker.appliance_nest_protect_downstairs
            name: Network
      - entity: device_tracker.appliance_nest_protect_upstairs
        type: custom:multiple-entity-row
        icon: mdi:smoke-detector
        name: Upstairs
        secondary_info: last-updated
        show_state: false
        entities:
          - entity: binary_sensor.nest_protect_upstairs_co_status
            name: CO
          - entity: binary_sensor.nest_protect_upstairs_heat_status
            name: Heat
          - entity: binary_sensor.nest_protect_upstairs_smoke_status
            name: Smoke
          - entity: binary_sensor.nest_protect_upstairs_battery_health
            name: Battery
          - entity: device_tracker.appliance_nest_protect_upstairs
            name: Network
    state_color: true
    show_header_toggle: false
    title: Nest Protect
    icon: si:google
    view_layout:
      position: sidebar
    header:
      type: picture
      image: /local/images/brand/nest-project-product.png
      tap_action:
        action: none
      hold_action:
        action: none
  - type: conditional
    conditions:
      - entity: input_boolean.debug_mode
        state: 'on'
    card:
      type: entities
      entities:
        - type: weblink
          url: x/appliances/Smoke-Alarms/Smoke-Alarms.md
          name: Household Wiki > Appliances > Smoke Alarms
          icon: si:markdown
        - type: weblink
          url: https://github.com/jcallaghan/home-assistant-config/issues/225
          name: '#225 Nest smoke alarm integration'
          icon: mdi:github
        - entity: group.smoke_alarms
        - entity: automation.security_smoke_alarms
          secondary_info: last-triggered
      title: Helpers
      state_color: true
      show_header_toggle: false
      theme: post-it
```
