### ISSUE TITLE
Read up on actionable alerts

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#232]
Read docs - https://companion.home-assistant.io/docs/notifications/actionable-notifications

I'm already using actionable alerts however I want to combine an alert for Android and iOS.

Passing a link to a Lovelace panel would be great too.
```
data:
  message: "Something happened at home!"
  data:
    actions:
      - action: "alarm" # The key you are sending for the event
        title: "Title" # The button title
      - action: "URI" # Must be set to URI if you plan to use a URI
        title: "Open Url"
        uri: "https://google.com"
```

I also see you can pass data with the alert which would avoid me duplicating my notification categories 
```
data:
  push:
    category: "alarm"
  action_data: # Anything passed in action_data will get echoed back to Home Assistant.
    entity_id: light.test
    my_custom_data: foo_bar
```

Consider critical alerts for security based notifications as these break through do not distrub.
```
    action:
    - service: notify.mobile_app_<your_device_id_here>
      data:
        title: "Wake up!"
        message: "The house is on fire and the cat's stuck in the dryer!"
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
```
