### ISSUE TITLE
Apple Watch actions ⌚😎🚀

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#239]
Create actions in Home Assistant mobile app to allow automations and scripts to be triggered via Apple Watch.

* TTS updates
* Security i.e. arm alarm
* Scenes like lights off
* Fun stuff like air freshener

Related: #232

**Comment by jcallaghan** [comment]
#HomeAssistant ```Mobile App``` documentation - https://companion.home-assistant.io/docs/core/core

**Comment by jcallaghan** [comment]
#HomeAssistant Mobile App ```Apple Watch``` documentation - https://companion.home-assistant.io/docs/apple-watch/apple-watch

**Comment by jcallaghan** [comment]
#HomeAssistant Mobile App ```Apple Watch Actions``` documentation - https://companion.home-assistant.io/docs/apple-watch/watch-actions/

**Comment by jcallaghan** [comment]
Once the action has been created in the mobile app, you can listen for the event being called via Developer Tools > Events > Listen to events ```ios.action_fired```. You can see more examples in the Watch Actions reference above.

Here is an example of a trigger I've added to an automation.
```
  # Apple Watch action
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: FRESH_ALL
```
