### ISSUE TITLE
Refactor critical notifications to use alert integration ⚠📲

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#257]
I use automations to send a number of notifications when an event such as a door or temperature is too low. While this works for one notification making it loop is a little tricky (less so with the new automation) but the ```alert``` integration is built for just this use-case. The [alert](https://www.home-assistant.io/integrations/alert) is also persistent is annoying and likely will lead to the event being corrected, particularly when TTS is used.

### Example alert
The following example will cause the alert to activate when ```binary_sensor.fridge_door_contact``` is ```on```. The alert will activate after 2 minutes (as skip_first is true) and repeat every 5 minutes. This is due to the repeat pattern I've provided.

```yaml
  kitchen_fridge_door:
    name: 'Fridge door left open'
    entity_id: binary_sensor.fridge_door_contact
    state: 'on'
    repeat:
      - 2
      - 5
    can_acknowledge: true
    skip_first: true
    title: '⚠️Fridge Door'
    message: 'The fridge door has been left open for {{ (as_timestamp(now()) - as_timestamp(states.binary_sensor.fridge_door_contact.last_updated)) | int //60 }} minutes.'
    done_message: 'The fridge door has been closed.'
    notifiers:
      - alert_kitchen
    data:
      apns_headers:
        apns-collapse-id: 'alert_acknowledgement'
      push:
        category: 'alert_acknowledgement'
        sound: 'Alert_WalkieTalkie_Haptic.caf'
      action_data:
        entity_id: alert.kitchen_fridge_door
```

### Automation to refactor
* [ ] Bath full #16 
* [ ] Fridge/freezer door left open #161.
* [ ] Fridge/freezer temperature too high or low #190.
* [ ] Critically low battery #120.
* [ ] Hot-tub lost power / temperature falling #160.
* [ ] Keys not returned #141.
* [ ] Chores based reminders milk #64 bottles or bin #52 hasn't been taken out.
* [ ] Oven on and temperature reminder #162.
* [ ] Exterior doors left open.
* [ ] Ground floor windows left open late evening and no motion has occurred in the room.

**Comment by jcallaghan** [comment]
#HomeAssistant Mobile App ```notification``` documentation - https://companion.home-assistant.io/docs/notifications/notifications-basic

**Comment by jcallaghan** [comment]
#HomeAssistant ```Mobile App``` documentation - https://companion.home-assistant.io/docs/core/core

**Comment by jcallaghan** [comment]
## Disabler alert via actionable notification
Additional to the ```alert``` integration I've also leveraged an actionable alert which allows me to disable the alert and stop it from repeating.

### iOS configuration
To achieve this I create a generic notification category in my iOS configuration.
```
ios:
  push:
    categories:
      - name: Alert
        identifier: 'alert_acknowledgement'
        actions:

          - identifier: 'alert_acknowledgement_disable'
            title: 'Disable alert?'
            authenticationRequired: false
            destructive: true
            behavior: 'default'
            activationMode: 'background'
```

### Notification group
Then in my alert group, I provide the alert entity_id in the action data that is sent back to Home Assistant with the actionable alert (category).

```
platform: group
name: alert_kitchen_fridge_door
services:

  - service: mobile_app_james_iphone
    data_template:
      title: 'Fridge'
      data:
        apns_headers:
          apns-collapse-id: "alert_kitchen_fridge_door"
        push:
          category: 'alert_acknowledgement'
          action_data:
            entity_id: alert.kitchen_fridge_door
```

### Disable alert automation
I then have an automation that is triggered when the ```ios.notification_action_fired``` is fired for this actionable alert ```ALERT_ACKNOWLEDGEMENT_DISABLE```.

**Comment by jcallaghan** [comment]
Shared on [Twitter](https://twitter.com/jamescallaghan/status/1289887361254400000).

**Comment by jcallaghan** [comment]
# message and done_message
If you add a ```message``` and ```done_message``` to your ```alert``` ```notify group``` configuration then these will be passed to the notification service unless you explicitly define a ```message``` with your service. 

```yaml
notify: 
  platform: group
  name: alert_kitchen_fridge_door
  services:

    - service: mobile_app_james_iphone
      data_template:
        title: 'Fridge'
        # message: ''
        data:
          apns_headers:
            apns-collapse-id: "alert_kitchen_fridge_door"
          push:
            category: 'alert_acknowledgement'
          action_data:
            entity_id: alert.kitchen_fridge_door

    - service: html5_notification
      data:
        title: 'Fridge'
        # message: ''

    - service: alexa_media
      data:
        target: ["media_player.alexa_kitchen","media_player.alexa_james_desk"]
open.'
        # message: ''
        data:
          type: 'announce'
          method: 'all'
```
