### ISSUE TITLE
BBQ safe to clean and close-up

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#31]
Clean a BBQ is an essential job that every BBQ needs. A little TLC goes a long way. I also have a cover for my BBQ that can only go over the BBQ once it has cooled. I'm going to create an automation to notify me when it is safe to clean and close up.

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/21#issuecomment-623144845_

**Comment by jcallaghan** [comment]
I have an input boolean that is enabled when the temperature rises above 100°C. 
```yaml
input_boolean:
  occupied_bbq:
    name: BBQ in-use
    initial: false
    icon: mdi:grill
```
When this is on and the BBQ ambient temperature falls below 40°C it will notify me via a HTML5 message to my PC's and a push notification to my phone.
```yaml
automation:
  alias: 'BBQ - Temperature okay to clean'

  trigger:

    - platform: numeric_state
      entity_id: sensor.esph_bbq_ambient_temperature
      below: '40'


  condition:

    - condition: and
      conditions:

      # check the automation has not run within the last 60 minutes
      - condition: template
        value_template: "{{ (as_timestamp(states.sensor.date_time.last_changed) - (as_timestamp(state_attr('automation.bbq_temperature_okay_to_clean','last_triggered')))) > 3600 }}"

      - condition: state
        entity_id: input_boolean.occupied_bbq
        state: "on"

  action:

    - service: notify.html5_notification
      data_template:
        title: "🍗 BBQ safe for cleaning"
        message: "The BBQ is at {{ states('sensor.esph_bbq_ambient_temperature') }}°C and safe for cleaning and closing up."

    - service: notify.ios_james_iphone
      data_template:
        title: "🍗 BBQ safe for cleaning"
        message: "The BBQ is at {{ states('sensor.esph_bbq_ambient_temperature') }}°C and safe for cleaning and closing up."

    - service: input_boolean.turn_off
      entity_id: input_boolean.occupied_bbq
```

Here is a screenshot of my Lovelace dashboard.
![image](https://user-images.githubusercontent.com/7449908/80920659-1f093100-8d69-11ea-8cac-f07baba8a362.png)

Also a screenshot of the notification on my phone.
