### ISSUE TITLE
Weather station - SGP30 TVOC and eCO2

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#36]
My SGP30 TVOC and eCO2 will be on the same board as my PM sensor so time to get this working too.

* [SGP30 Air Quality Sensor Breakout](https://www.amazon.co.uk/gp/product/B08258HPSY)
* [ESPHome](https://esphome.io/components/sensor/sgp30.html)
* [Pimoroni](https://shop.pimoroni.com/products/sgp30-air-quality-sensor-breakout)
* [Adafruit](https://www.adafruit.com/product/3709)

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/13#issuecomment-623392099_

**Comment by jcallaghan** [comment]
Had issues with ESPHome finding a device when I was using the default i2c pins. In the log, I would get an error saying ```Found no i2c devices```. When I change to using the second i2c pins it found my sensor. 

```yaml
i2c:

  - id: i2c_1
    sda: 21
    scl: 22
    scan: True
    
  - id: i2c_2
    sda: 33
    scl: 32
    scan: True

sensor:

  - platform: sgp30
    i2c_id: i2c_2
    eco2:
      name: "${system_name}_eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "${system_name}_TVOC"
      accuracy_decimals: 1
    address: 0x58
    update_interval: 5s
```
![image](https://user-images.githubusercontent.com/7449908/80965416-65629c80-8e0a-11ea-9337-0172c48377ca.png)
