### ISSUE TITLE
Weather station - Dew point 🥶❄💧

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#44]
# Dew point

Given I have data for air temperature and humidity I can calculate the [dew point](https://en.wikipedia.org/wiki/Dew_point).

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/13#issuecomment-624340416_

**Comment by jcallaghan** [comment]
Inspired by the [Manchester University weather station](http://whitworth.cas.manchester.ac.uk/current/index.html) I discovered I was missing dew point amongst my planned data. When I research how this value was calculated I [found there was a formula to work this out the Magnus Dew Point from the air temperature and humidity](https://www.calcunation.com/calculator/dew-point.php).

So I took off to dev-tools and started trying to create this in the template editor.
```yaml
Humidity: {{ states('sensor.weather_station_temperature_humidity') }}
Temperature:  {{ states('sensor.weather_station_temperature') }}

{% set gamma = ((states('sensor.weather_station_temperature_humidity') | int) / 100) + ((17.62 * (states('sensor.weather_station_temperature') | int)) / (243.12 + (states('sensor.weather_station_temperature') | int))) %}
{{ ((243.12 * gamma) / (17.62 - gamma) / 10) | round(2) }}
```
And look at that...I'm reading similar to the University.

![image](https://user-images.githubusercontent.com/7449908/81122409-bff21a80-8f28-11ea-975e-fe7b99c92c43.png)

![image](https://user-images.githubusercontent.com/7449908/81122413-c1bbde00-8f28-11ea-9051-c62547a2e3b9.png)

**Comment by jcallaghan** [comment]
Here is the sensor template 

```yaml
sensor:
  platform: template
  sensors:
    dew_point:
      friendly_name_template: "Dew Point"
      value_template: >-
        {% set gamma = ((states('sensor.weather_station_temperature_humidity') | int) / 100) + ((17.62 * (states('sensor.weather_station_temperature') | int)) / (243.12 + (states('sensor.weather_station_temperature') | int))) %}
        {{ ((243.12 * gamma) / (17.62 - gamma) / 10) | round(2) }}
      unit_of_measurement: '°C'
```
