### ISSUE TITLE
Household bin automation

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#52]
Draft content:
* calendar integration
* alarm and bin day TTS reminder
* bin emptied notification

**Comment by jcallaghan** [comment]
Draft: Bin emptied notification

**Comment by jcallaghan** [comment]
## Lovelace card

![image](https://user-images.githubusercontent.com/7449908/157895891-d4ba6a30-5afc-4222-bf70-17dfb9f9d854.png)

```yaml
{% if now().strftime('%a') == "Thu" or (now().strftime('%a') == "Fri" and is_state('input_boolean.chore_take_bin_out','on'))  %}
  {% if states('sensor.calendar_house_bin') == "⬜ Grey bin (waste)" %}
    [![image](/local/images/bins/bins_clear_indicator_waste.png)](/lovelace-config/bins)
  {% elif states('sensor.calendar_house_bin') == "🟦 Blue bin (paper and card)" %}
    [![image](/local/images/bins/bins_clear_indicator_paper.png)](/lovelace-config/bins)
  {% elif states('sensor.calendar_house_bin') == "⬛ Black bin (mixed recycling)" %}
    [![image](/local/images/bins/bins_clear_indicator_mixed.png)](/lovelace-config/bins)
  {% endif %} 
{% endif %} 
This week is {{ states('sensor.calendar_house_bin') }}.
```

**Comment by jcallaghan** [comment]
## Notifications

### iOS

First. Credit to the Companion app team, not just for an amazing app but also for amazing documentation and how fast they release new features etc.

![image](https://user-images.githubusercontent.com/7449908/157902321-789a6298-ee1b-4ddf-8986-d58277440534.png)

Tip! Actions on iOS make use of [SF Symbols](https://developer.apple.com/sf-symbols/) and I found a [useful site[(https://hotpot.ai/free-icons?s=sfSymbols) which make them searchable. This is how I tracked down ```sfsymbols:checkmark``` and ```sfsymbols:speaker.slash.rtl```.

Here is an example. 

```yaml
service: notify.james
data:
  title: "⚠️ Chore - Household bin"
  message: "The {{ bin }} needs to be taken out."
  data:
    group: "chore"
    tag: "bin_day"
    url: "/lovelace-config/bins"
    image: "/local/images/bins/bins_clear_indicator_mixed.png"
    attachment:
      hide-thumbnail: true        
    push:
      interruption-level: time-sensitive       
    actions:
      - action: "chore_bin_day_completed"
        title: "Chore completed"
        icon: "sfsymbols:checkmark"
      - action: "chore_bin_day_silence"
        title: "Silence for 1 hour"
        icon: "sfsymbols:speaker.slash.rtl"       
```

### HTML5

I use the [HTML5 integration](https://www.home-assistant.io/integrations/html5) to send notifications to the computers we regularly use. These are fantastic given how much time we spend at our workstations and it is great you can make these actionable.

![image](https://user-images.githubusercontent.com/7449908/157901357-85f18d67-608c-410d-bb78-dd0cefe6a743.png)

Here is an example.

```yaml
service: notify.html5
data:
  title: ⚠️ Chore - Household bin
  message: Remember to take out the mixed recycling.
  data:
    renotify: 1
    image: /local/images/bins/bins_clear_indicator_mixed.png
    actions:
      - action: "chore_bin_day_completed"
        title: "Chore completed ✔️"
      - action: "chore_bin_day_silence"
        title: "Silence for 1 hour 💤"
```

**Comment by jcallaghan** [comment]
## WLED bin shed lighting

When I get round to building a bin shed this summer I plan to include an addressable LED strip. I'll use this to provide useful lighting when accessing the bins but also to indicate which bins are due out. 

I was inspired by this [post](https://twitter.com/jamescallaghan/status/1463123079010336773) in the [Home Assistant community site](https://community.home-assistant.io/t/garbage-and-recycling-collection-notifier-light/217226).

![image](https://user-images.githubusercontent.com/7449908/157910539-8fbc5f36-c069-4e9c-a601-3e1d33101ca7.png)

**Comment by jcallaghan** [comment]
## Automatic detection

Previously before I moved I had vibration sensors attached under the lids so I could automatically detect if the bin had been taken out. I must get back round installed these again. 

![image](https://user-images.githubusercontent.com/7449908/84300687-82496880-ab4a-11ea-898e-f57699b3991f.jpeg)

**Comment by jcallaghan** [comment]
## Lovelace card

I display the following template in the markdown lovelace card on my main view. It only shows the graphic the day before and the day of collection. Once the bin has been taken out it is no longer shown.

![image](https://user-images.githubusercontent.com/7449908/157895891-d4ba6a30-5afc-4222-bf70-17dfb9f9d854.png)

```yaml
{% if now().strftime('%a') == "Thu" or (now().strftime('%a') == "Fri" and is_state('input_boolean.chore_take_bin_out','on'))  %}
  {% if states('sensor.calendar_house_bin') == "⬜ Grey bin (waste)" %}
    [![image](/local/images/bins/bins_clear_indicator_waste.png)](/lovelace-config/bins)
  {% elif states('sensor.calendar_house_bin') == "🟦 Blue bin (paper and card)" %}
    [![image](/local/images/bins/bins_clear_indicator_paper.png)](/lovelace-config/bins)
  {% elif states('sensor.calendar_house_bin') == "⬛ Black bin (mixed recycling)" %}
    [![image](/local/images/bins/bins_clear_indicator_mixed.png)](/lovelace-config/bins)
  {% endif %} 
{% endif %} 
This week is {{ states('sensor.calendar_house_bin') }}.
```
I also have a separate view where I make all the config/helpers available. At first the view is limited but if you edit the view or enable a debug helper then additional cards are show (via a condition) with the helpers etc relating to this use-case.

![image](https://user-images.githubusercontent.com/7449908/157899989-92cba868-c6d0-468f-931f-173901694903.png)

Here is an example of the additional cards.

![image](https://user-images.githubusercontent.com/7449908/157900492-db7dbac4-60e3-4360-a540-0482b389c3f7.png)
 
```yaml
type: conditional
conditions:
  - entity: input_boolean.debug_mode
    state: 'on'
card:
  type: entities
  entities:
    - type: weblink
      url: https://github.com/jcallaghan/home-assistant-config/issues/52
      name: '#52 Household bins'
    - entity: input_boolean.chore_take_bin_out
    - entity: calendar.house_bin
    - entity: sensor.calendar_house_bin
    - entity: automation.chore_house_take_out_bin_reminder
      secondary_info: last-triggered
  title: Helpers
  state_color: true
  show_header_toggle: false
```
