### ISSUE TITLE
Bin emptied notification

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#53]
### Bin emptied notification
* Aqara vibration sensor.
* Home Assistant automation.
* Notification integration - HTML5 + phone.

_Originally posted by @jcallaghan in https://github.com/jcallaghan/home-assistant-config/issues/52#issuecomment-626000161_

**Comment by jcallaghan** [comment]
# Calendar integration
I have set up two reoccurring events in my calendar for the weekly rubbish and recycling collection day. I adjust the occurrence accordingly to account for bank holidays etc. Using the Google Calendar integration I am able to add a search pattern ```search: '* Bin'``` which creates a binary_sensor that becomes active on collection days. 

![image](https://user-images.githubusercontent.com/7449908/84020805-56c45380-a97b-11ea-86ec-6671ced6b962.png)

Additionally, I have created a secondary template sensor that displays the name of the next event and has the event details as attributes.

```yaml
platform: template
sensors:
  calendar_house_bin:
    friendly_name: 'Next Bin'
    value_template: >
      {{ state_attr('calendar.house_bin','message') }}
    attribute_templates:
      description: >-
        {{ state_attr('calendar.house_bin','description') }}
      location: >-
        {{ state_attr('calendar.house_bin','location') }}
      start_time: >-
        {{ state_attr('calendar.house_bin','start_time') }}
      end_time: >-
        {{ state_attr('calendar.house_bin','end_time') }}
    icon_template: mdi:trash-can
```

![image](https://user-images.githubusercontent.com/7449908/84020849-6c397d80-a97b-11ea-8880-4ca6748a8f3a.png)

I use some of this information in my good morning routine.
