### ISSUE TITLE
Managing low batteries with dashboards, notifications and automations 🔋

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#60]
# Objective
Receive a notification when batteries are getting critical ```< 10%``` or low ```10%-20%``` or those that are unavailable. 

# Features
* [x] Lovelace panel to track battery levels.
* [x] Entity filter card to provide a focused view of low and critical batteries.
* [x] Daily automation to provide notification of low batteries (persistent but not annoyingly so).
* [x] Automated pro-active maintenance process (DevOps) to create GitHub issue when device has a low battery. #103 
* [x] TTS announcements.
* [x] Grafana dashboards to provide useful insights into battery data.  

Related to #51, #103

**Comment by jcallaghan** [comment]
## Lovelace 
Firstly before I kick any automation I decided to do create the Lovelace panel to give me a view of things. Want this has shown me is I had a sh*t load of batteries yet I've never really had a problem with this.

![image](https://user-images.githubusercontent.com/7449908/81913952-90967a00-95c8-11ea-8595-6e3608215c4c.png)

## Low and Critical Batteries
After getting all the devices into cards I decided to add to filter cards to show me devices with low batteries (<20%) and those with critical batteries (unavailable or less than 20%).

![image](https://user-images.githubusercontent.com/7449908/81914538-57aad500-95c9-11ea-8450-97c394ca402e.png)

### Critical battery filter card
The critical battery filter card uses two filters and looks like this:

```yaml
card:
  show_header_toggle: false
  title: Critical Batteries
entities:
  - entity: sensor.battery
state_filter:
  - operator: <
    value: 10
  - operator: ==
    value: unavailable
type: entity-filter
```

### Low battery filter card
The low battery filter card looks like this:

```
card:
  show_header_toggle: false
  title: Critical Batteries
entities:
  - entity: sensor.battery
state_filter:
  - operator: <
    value: 20
type: entity-filter
```

**Comment by jcallaghan** [comment]
# Grafana 
I was interested to see how long it was between batteries cycles so I've created a dashboard to report on battery levels. This example is of the devices in my back garden but I'm curious if I should do this on a room-by-room basis or by a thing-type basis such as Ring, Aqara, Hue etc.

![image](https://user-images.githubusercontent.com/7449908/83364175-2dae2c80-a397-11ea-9aad-0557f66e237e.png)

**Comment by jcallaghan** [comment]
# Automation
Leverage examples such as:
* https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/packages/battery_levels.yaml
* https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/packages/battery_levels.yaml?rgh-link-date=2017-11-23T16%3A30%3A11Z
* https://community.home-assistant.io/t/howto-create-battery-alert-without-creating-a-template-for-every-device/30576/34
* https://community.home-assistant.io/t/how-do-i-trigger-based-on-a-substring-of-a-bunch-of-sensors/3164/17?u=tscibilia

**Comment by jcallaghan** [comment]
# Observations

Few observations I have made during this exercise.
* [ ] Hue outdoor sensors can't be reporting correctly as they have shown 100% since the start of the dataset.
* [ ] I can't seem to the data back for the battery level of my Ring Alarm entities where this is help as an attribute alongside the main binary_sensor entity.

![image](https://user-images.githubusercontent.com/7449908/83437178-322a2200-a437-11ea-9b9b-c7921269e094.png)

**Comment by jcallaghan** [comment]
[Shared on Twitter](https://twitter.com/jamescallaghan/status/1267561256350818304).

**Comment by jcallaghan** [comment]
# Battery level gauges

[Rui Espinho](https://twitter.com/ruiespinho/status/1267583038889889794) asked on Twitter how I made the batter level gauges. These are made by leveraging the bar gauge visualisation in a Grafana dashboard along with some thresholds to align to my low (20%) and critical levels (10%).

![image](https://user-images.githubusercontent.com/7449908/83462294-be057380-a462-11ea-9cae-f511726519fc.png)

**Comment by jcallaghan** [comment]
# How to: Grafana queries
[Matthias Matousek (@m_matou) asked on Twitter](https://twitter.com/m_matou/status/1267755186556190720) how I achieve the queries for batteries.

Depending on how the battery data is reported you may need to try different queries.

## State method



## Attribute method

**Comment by jcallaghan** [comment]
# Todo
* Automation/package https://raw.githubusercontent.com/notoriousbdg/Home-AssistantConfig/master/packages/battery_alert.yaml
* Attribute-based battery level - Ring alarm sensors
* Monitor 100% batteries - if they're not moving something might be wrong with the reporting
* Does Tado publish battery via API? 
* Home Assistant notification
* Morning TTS routine
* Dynamic filter card to avoid having to keep my Lovelace panel and cards up-to-date

**Comment by jcallaghan** [comment]
# History
```
history:
  exclude:
    entities:
      - automation.battery_persistent_notification
      - automation.battery_persistent_notification_clear
      - automation.battery_notification_default
      - automation.battery_notification_slack
      - automation.battery_sensor_from_attributes
      - automation.update_battery_status_group_members
      - automation.update_battery_low_group_members
      - automation.remove_battery_low_group
      - automation.delete_battery_sensor
```

**Comment by jcallaghan** [comment]
# GitHub API

## Testing

So it was always going to end up here in my view. Automated maintenance tasks. It was more deciding to use issues in this repo or creating a task in Microsoft Todo. I may still do this for testing and fun anyway. 

Leveraging [Postman](https://www.postman.com/) to test the GitHub API I was able to create a new issue. Postman is great for testing APIs! You can also use parameters in the URL to fill prepare an issue: ```https://github.com/jcallaghan/home-assistant-config/issues/newtitle=test&body=test&labels=battery,task:%20maintenance```.

![image](https://user-images.githubusercontent.com/7449908/84328570-34e4ef80-ab7a-11ea-86b8-6b9a3ec92c2e.png)

1. Generate new personal access token (with full repo access) ```https://github.com/settings/tokens```
1. API POST endpoint ```https://api.github.com/repos/jcallaghan/home-assistant-config/issues```
1. Set authentication method to Oauth using the access token generated above
1. Body
```JSON
{
  "title": "Test",
  "body": "Test",
  "labels": [
    "battery",
    "task: maintenance"
  ]
}
```
## Rest command
Using the rest_command integrated I created the following service.
```
rest_command:
  new_github_issue_replace_battery:
    url: https://api.github.com/repos/jcallaghan/home-assistant-config/issues
    method: POST
    headers:
      Authorization: !secret github_token
    payload: '{"title":"{{ title }}","body":"{{ message }}","labels":["battery","task: maintenance"]}'
```

### secrets.yaml
Don't forget to add ```Bearer ``` in front of your access token in your secrets file.
```
github_token: "Bearer 000000000000000"
```

## Automation/service

Service name:
```rest_command.new_github_issue_replace_battery```
Service data: 
```
{ 
  "title": "Service test",
  "message": "Create via service call in Home Assistant"
}
```
![image](https://user-images.githubusercontent.com/7449908/84329850-bbe79700-ab7d-11ea-98ee-f7ac1099741d.png)

## Reference
* https://developer.github.com/v3/issues/#create-an-issue
* https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens
* https://www.postman.com/
* https://developer.github.com/v3/
* https://www.home-assistant.io/integrations/rest_command/
