### ISSUE TITLE
Add journal events into the logbook

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#80]
### Background 
I added an ```input_text``` entity to allow me to capture notes about events that are happening within my home through natural language. An example might be ```Kitchen fan automation didn't trigger as expected```. The idea of this was to use this when studying the data in Grafana and add these notes as annotations to relevant dashboards. 

### Objective
Leverage the [logbook integration](https://www.home-assistant.io/integrations/logbook/) and it's service ```service: logbook.log``` to record things into the logbook.

```
 - service: logbook.log
   data:
     name: Kitchen
     message: is being used
     entity_id: light.kitchen
     domain: light
```
