### ISSUE TITLE
Tomorrows weather forecast 📅☔

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#87]
# Objective.
It rained and I forgot to cover up the garden furniture yesterday. I want to leverage my weather station data to forecast deteriorating weather conditions and rain and provide notification when it is worsening.

# Ideas
* Levage my weather station.
* Utilise the Norwegian Meteorological Institute integration.
* Notification if the weather is deteriorating.
* Provide a forecast summary within the night/morning TTS notification.
* Add a contact like a sensor to the table and cover to provide a condition if the furniture is covered or not.

Related: #13

**Comment by jcallaghan** [comment]
# Norwegian Meteorological Institute
The weather integration from NMI provides local weather data based on the location in the configuration. This is available through an entity like ```weather.the_retreat```.

This entity has a number of attributes that provide a summary of today's weather along with a five-day forecast.

Using ```Developer Tools > Template``` we can explore the attributes this entity contains using ```{{ states.weather.the_retreat }}```. This provides the following output:

```yaml
<template state weather.the_retreat=partlycloudy; 
  temperature=13.2, 
  humidity=59, 
  pressure=1011.2, 
  wind_bearing=27.7, 
  wind_speed=18.7, 
  attribution=Weather forecast from met.no, delivered by the Norwegian Meteorological 
 Institute., 
  forecast=[
   {'datetime': datetime.datetime(2020, 6, 4, 12, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), 
     'temperature': 12.0, 
     'condition': 'rainy', 
     'pressure': 1004.8, 
     'humidity': 64.5, 
     'wind_speed': 13.0, 
     'wind_bearing': 294.3}, 
   {'datetime': datetime.datetime(2020, 6, 5, 12, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>),
     'temperature': 11.0, 
     'condition': 'rainy', 
     'pressure': 997.1, 
     'humidity': 80.8, 
     'wind_speed': 17.3, 
     'wind_bearing': 300.7},
   {'datetime': datetime.datetime(2020, 6, 6, 12, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), 
     'temperature': 7.6, 
     'condition': 'rainy', 
     'pressure': 996.8, 
     'humidity': 87.5, 
     'wind_speed': 29.2, 
     'wind_bearing': 267.2}, 
   {'datetime': datetime.datetime(2020, 6, 7, 12, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), 
     'temperature': 14.5, 
     'condition': 'partlycloudy', 
     'pressure': 1004.8, 
     'humidity': 57.8, 
     'wind_speed': 21.6, 
     'wind_bearing': 21.2},
   {'datetime': datetime.datetime(2020, 6, 8, 12, 0, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), 
     'temperature': 15.8, 
     'condition': 'cloudy', 
     'pressure': 1016.5, 
     'humidity': 50.3, 
     'wind_speed': 14.8, 
     'wind_bearing': 30.1}
   ], 
  friendly_name=The Retreat @ 2020-06-03T18:31:35.601035+01:00>
```

# Tomorrow's weather forecast
Using ```{{ states.weather.the_retreat.attributes.forecast[0] }}``` we can see the weather forecasted for tomorrow. Replacing ```[0]``` with ```1```, ```2```,```3``` and ```4``` will push out the forecast accordingly.

Dialling this in a little more we can fetch specific attributes in the forecast such as the condition ``` {{ states.weather.the_retreat.attributes.forecast[0].condition }} ``` and temperatures ``` {{ states.weather.the_retreat.attributes.forecast[0].temperature }}```.

## Today tomorrow example
```yaml
Now
Condition: {{ state_attr('weather.the_retreat','condition') }}
Temperature: {{ state_attr('weather.the_retreat','temperature') }}
Humidity: {{ state_attr('weather.the_retreat','humidity') }}
Pressure: {{ state_attr('weather.the_retreat','pressure') }}
Wind speed: {{ state_attr('weather.the_retreat','wind_speed') }} 
Wind bearing: {{ state_attr('weather.the_retreat','wind_bearing') }}

Now
Condition: None
Temperature: 12.7
Humidity: 56
Pressure: 1011.1
Wind speed: 16.2 
Wind bearing: 24.6

Tomorrow:
Condition: {{ states.weather.the_retreat.attributes.forecast[0].condition }}
Temperature: {{ states.weather.the_retreat.attributes.forecast[0].temperature }}
Humidity: {{ states.weather.the_retreat.attributes.forecast[0].humidity }}
Pressure: {{ states.weather.the_retreat.attributes.forecast[0].pressure }}
Wind speed: {{ states.weather.the_retreat.attributes.forecast[0].wind_speed }}
Wind bearing: {{ states.weather.the_retreat.attributes.forecast[0].wind_bearing }}

Tomorrow:
Condition: rainy
Temperature: 12.0
Humidity: 64.5
Pressure: 1004.8
Wind speed: 13.0
Wind bearing: 294.3
```

![image](https://user-images.githubusercontent.com/7449908/83675668-4f92f380-a5d1-11ea-94d0-6e4b9f711773.png)
