### ISSUE TITLE
Update notify service calls

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/home-assistant-config#88]
Upgrade any ```notify.ios*``` service calls and replace with ```notify.mobile_app_*```. This will allow replaceable notifications to work correctly. 

```
  - service: notify.mobile_app_jamess_iphone
    data_template:
      title: 🥛 Milkman
      message: "The milk crate needs to be taken outside."
      data:
        apns_headers:
          apns-collapse-id: "milkman_take_out_reminder"
```

https://companion.home-assistant.io/docs/getting_started/migration/

_Originally posted by @CCOSTAN in https://github.com/CCOSTAN/Home-AssistantConfig/issues/750#issuecomment-638993132_
